let mapleader = ";"
set hidden
set scrolloff=5
set encoding=UTF-8
filetype on 
set nobackup
set nowritebackup
set cmdheight=1
set updatetime=300
set signcolumn=yes
set sw=4
set ts=4
set tabstop=4
set clipboard=unnamed
set foldcolumn=0 
set nofoldenable
set signcolumn=yes 
set cursorline
set virtualedit=block,onemore
set autoindent
set nobackup
set noswapfile
set numberwidth=1
set nu
set hidden
set shortmess+=c
set updatetime=100
set termguicolors
set expandtab
set fo-=r
