local tool = require("core.tool")
local M = {}
M.lsp_server = {
  "pyright",
  "cmake",
  "bashls",
  "vimls",
  "texlab",
  "jsonls",
  "vuels",
  "clangd",
  "sumneko_lua",
  "jdtls",
  "gopls",
  --"csharp_ls",
  --"r_language_server",
  --"rust_analyzer",
  --"julials",
  "pylsp",
  --"tsserver",
  --"omnisharp",
  --"fsautocomplete",
  --"hls",
  --"dartls",
  --"vala_ls",
  --"volar",
  --"kotlin_language_server",
  --"jedi_language_server",
  --"cssls",
  --"lemminx",
  --"groovyls",
  --"graphql",
  --"html",
  --"yamlls",
  --"ocamllsp",
  --"denols",
  --"taplo",
}
return M
